### ISSUE TITLE
Reloading with harmony 2.0 causes crash

### ISSUE THREAD

**Issue by lucianposton** [newman55/unity-mod-manager#48]
```
  at <unknown> <0xffffffff>
  at System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>.FindEntry (TKey_REF) [0x0001b] in <e1a80661d61443feb3dbdaac88eeb776>:0
  at System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>.TryGetValue (TKey_REF,TValue_REF&) [0x00000] in <e1a80661d61443feb3dbdaac88eeb776>:0
  at HarmonyLib.AccessCache.Get<T_REF> (System.Collections.Generic.Dictionary`2<System.Type, System.Collections.Generic.Dictionary`2<string, T_REF>>,System.Type,string,System.Func`1<T_REF>) [0x00000] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.AccessCache.GetFieldInfo (System.Type,string,HarmonyLib.AccessCache/MemberType,bool) [0x0001b] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.Traverse.Field (string) [0x00023] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.Traverse/<>c__DisplayClass39_0.<IterateFields>b__0 (string) [0x00000] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at System.Collections.Generic.List`1<T_REF>.ForEach (System.Action`1<T_REF>) [0x00024] in <e1a80661d61443feb3dbdaac88eeb776>:0
  at HarmonyLib.Traverse.IterateFields (object,object,System.Action`3<string, HarmonyLib.Traverse, HarmonyLib.Traverse>) [0x0002b] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.AccessTools.MakeDeepCopy (object,System.Type,System.Func`4<string, HarmonyLib.Traverse, HarmonyLib.Traverse, object>,string) [0x00232] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.AccessTools.MakeDeepCopy<T_REF> (object) [0x00000] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.HarmonyMethodExtensions.GetHarmonyMethodInfo (object) [0x00045] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at HarmonyLib.HarmonyMethodExtensions/<>c.<GetFromType>b__5_0 (object) [0x00000] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at System.Linq.Enumerable/SelectArrayIterator`2<TSource_REF, TResult_REF>.MoveNext () [0x0003a] in <839a3cb835c04d14aeb58d83bb7bc4bd>:0
  at System.Linq.Enumerable/WhereEnumerableIterator`1<TSource_REF>.ToList () [0x00030] in <839a3cb835c04d14aeb58d83bb7bc4bd>:0
  at System.Linq.Enumerable.ToList<TSource_REF> (System.Collections.Generic.IEnumerable`1<TSource_REF>) [0x0001f] in <839a3cb835c04d14aeb58d83bb7bc4bd>:0
  at HarmonyLib.HarmonyMethodExtensions.GetFromType (System.Type) [0x0004f] in <2c24e61813ae412c85ffcdf9d30118fc>:0
  at ModMaker.ModManager`2<TCore_REF, TSettings_REF>.Enable (UnityModManagerNet.UnityModManager/ModEntry,System.Reflection.Assembly) [0x0013f] in <eb86ee6dbbc54673ad1979bfb926920c>:0
  at CallOfTheTabletop.Main.OnToggle (UnityModManagerNet.UnityModManager/ModEntry,bool) [0x0000d] in <eb86ee6dbbc54673ad1979bfb926920c>:0
  at UnityModManagerNet.UnityModManager/ModEntry.set_Active (bool) [0x0006a] in <911803aec7f1462e823e388dbe7ecc67>:0
  at UnityModManagerNet.UnityModManager/ModEntry.Load () [0x00811] in <911803aec7f1462e823e388dbe7ecc67>:0
  at UnityModManagerNet.UnityModManager/ModEntry.Reload () [0x00132] in <911803aec7f1462e823e388dbe7ecc67>:0
  at UnityModManagerNet.UnityModManager/UI.DrawTab (int,UnityEngine.Events.UnityAction&) [0x0077b] in <911803aec7f1462e823e388dbe7ecc67>:0
  at UnityModManagerNet.UnityModManager/UI.WindowFunction (int) [0x000c7] in <911803aec7f1462e823e388dbe7ecc67>:0
  at UnityEngine.GUILayout/LayoutedWindow.DoWindow (int) [0x00077] in <14785407b2184ffc9b3039c64591325d>:0
  at UnityEngine.GUI.CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle) [0x00077] in <14785407b2184ffc9b3039c64591325d>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object_int_int_object_int_single_single_object (object,intptr,intptr,intptr) [0x0001e] in <14785407b2184ffc9b3039c64591325d>:0
```

Harmony's AccessCache was made `readonly` in 2.0. See https://github.com/pardeike/Harmony/commit/112f2ebaf0d4987ea9222d30d886ca8176f242da#diff-565ed52cb1a194629139db6eaa90ced6L41

It seems that due to this change, the above crash occurs during reload when harmony trys to call methods in the AccessCache after UMM has set the readonly field to a new instance.

**Comment by newman55** [comment]
Strange, it always worked for me. Apparently this is a weird JIT.

**Comment by lucianposton** [comment]
Yea, I'm thinking there is some kind of JIT optimization performed under the assumption that the field never changes (as indicated by the `readonly` keyword), and changing the field via reflection causes the crash. I'm not certain though. I couldn't find anything definitely indicating that `readonly` is used for JIT optimization for reference types (it does for primitive types (or maybe it was for value types? I forget)).

**Comment by lucianposton** [comment]
> Strange, it always worked for me. Apparently this is a weird JIT.

Also, there was a race condition. Sometimes, I would have to reload it a few times before the crash occurred (maybe after GC ran).

**Comment by newman55** [comment]
Does it work in the main thread?

**Comment by lucianposton** [comment]
Yea, pretty sure that code is run in the main thread. The UI is locked while reloading, and the abort is in the main thread, looking at the native stacktrace.

```
Native stacktrace:

Thread 1 (Thread 0x7f9b26091740 (LWP 27198)):
#0  0x00007f9b2663f9ae in waitpid () at /lib64/libpthread.so.0
#1  0x00007f9b1ff85129 in  () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#2  0x00007f9b26640060 in <signal handler called> () at /lib64/libpthread.so.0
#3  0x00007f9b260cc601 in raise () at /lib64/libc.so.6
#4  0x00007f9b260b655b in abort () at /lib64/libc.so.6
#5  0x00007f9b200c8ff8 in  () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#6  0x00007f9b200d9388 in monoeg_g_logv () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#7  0x00007f9b200d94b9 in monoeg_assertion_message () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#8  0x00007f9b1ff8d02f in  () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#9  0x00007f9b1ff90c5b in  () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#10 0x00007f9b1ff86e85 in  () at /home/lp/gamesdata/GOG Games/Pathfinder Kingmaker/game/Kingmaker_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
#11 0x0000000040116893 in  ()
#12 0x0000000002bc92c5 in  ()
#13 0x01007f9b00000000 in  ()
#14 0x00007ffed57f94d0 in  ()
#15 0x00007ffed57f9308 in  ()
#16 0x0000000002bd83d0 in  ()
#17 0x0000000000000000 in  ()
```
